function TratarErro(){
    try{valorInexistente
    }catch(e){
        console.log("Ocoorreu um erro: ")
    }
}